ARG DISTROLESS_IMAGE="quay.io/quarkus/quarkus-distroless-image:2.0-2026-05-24@sha256:880e43859cc1301a4db5b781ef9835d36a529c2539e75d9104eaf60833207968"

FROM ${DISTROLESS_IMAGE} AS runner
ARG APP_DIR=/deployment
ARG UID=1001

USER root
WORKDIR ${APP_DIR}
COPY \
  --chmod=111 \
   target/*-runner ${APP_DIR}/application

ENV LANGUAGE='en_US:en'
USER ${UID}:${UID}
ENTRYPOINT [ "./application" ]
